### ISSUE TITLE
mappings element with multiple directories causes no such file of directory

### ISSUE THREAD

**Issue by jtougas** [rquadling/bower-installer#160]
If the destination in one of the mapping elements is more than one directory deep I'm getting an error. For example: 
```
"tinymce": {
    "mapping": [
        {"bower_components/tinymce/tinymce.js": "tinymce.js"},
        {"bower_components/tinymce/themes/modern/theme.js": "theme/modern/theme.js"}
    ]
}
```

results in 
```Running bower install...Finished
Installing:
C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\node_modules\q\q.js:126
                    throw e;
                    ^

Error: ENOENT: no such file or directory, mkdir 'C:\dev\projects\bower-installer-mkdirp\target\tinymce\theme\modern'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.fs.mkdirSync (C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\node_modules\node-fs\lib\fs.js:103:7)
    at installFile (C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\lib\installer.js:80:17)
    at C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\lib\installer.js:166:13
    at C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\node_modules\async\lib\async.js:111:13
    at Array.forEach (native)
    at _each (C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\node_modules\async\lib\async.js:32:24)
    at Object.async.each (C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\node_modules\async\lib\async.js:110:9)
    at Object.installDependency (C:\Users\jtougas\AppData\Roaming\npm\node_modules\bower-installer\lib\installer.js:159:11)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bug"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! bower-installer-mkdirp@1.0.0 bug: `rm -r bower_components & bower install & rm -r target & bower-installer`
npm ERR! Exit status 1
```

Perhaps there is another way of doing this?

To reproduce: https://github.com/jtougas/bower-installer-mkdirp

**Comment by rquadling** [comment]
Yep! Found and fixed. Releasing it in a few minutes.

Thank you for your report.
