### ISSUE TITLE
TypeError: Cannot read property 'ignore' of undefined

### ISSUE THREAD

**Issue by aristidesfl** [rquadling/bower-installer#162]
bower 1.8.0
node v6.9.1

```
$ bower-installer
Setting up install paths...Finished
Running bower install...Finished
Installing:
/usr/local/lib/node_modules/bower-installer/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property 'ignore' of undefined
    at /usr/local/lib/node_modules/bower-installer/bower-installer.js:149:19
    at /usr/local/lib/node_modules/bower-installer/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/usr/local/lib/node_modules/bower-installer/node_modules/async/dist/async.js:941:9)
    at eachOf (/usr/local/lib/node_modules/bower-installer/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/usr/local/lib/node_modules/bower-installer/node_modules/async/dist/async.js:3089:3)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower-installer/bower-installer.js:133:15)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/local/lib/node_modules/bower-installer/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower-installer/node_modules/bower/lib/commands/index.js:45:25

```

**Comment by blittle** [comment]
@aristidesfl can you also post your bower config?

**Comment by aristidesfl** [comment]
I've was using .bowerrc for bower-installer configurations by mistake. 
Might be a good idea to check if bower.json doesn't contain bower-installer configuration and throw a informative error message.
